CREATE TABLE IF NOT EXISTS roles (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(40) NOT NULL UNIQUE,
  name VARCHAR(80) NOT NULL,
  permissions TEXT NOT NULL,
  is_system TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  pass_hash VARCHAR(255) NOT NULL,
  role_id INT UNSIGNED NOT NULL,
  status ENUM('active','disabled') NOT NULL DEFAULT 'active',
  last_login DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (role_id) REFERENCES roles(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settings (
  k VARCHAR(80) PRIMARY KEY,
  v MEDIUMTEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS categories (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(80) NOT NULL UNIQUE,
  name_hi VARCHAR(160) NOT NULL,
  name_en VARCHAR(160) NOT NULL DEFAULT '',
  icon VARCHAR(16) NOT NULL DEFAULT '',
  color VARCHAR(7) NOT NULL DEFAULT '#eef2ff',
  sort INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS posts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  type ENUM('yojna','page') NOT NULL DEFAULT 'yojna',
  slug VARCHAR(160) NOT NULL,
  category_id INT UNSIGNED NULL,
  icon VARCHAR(16) NOT NULL DEFAULT '',
  title_hi VARCHAR(255) NOT NULL,
  title_en VARCHAR(255) NOT NULL DEFAULT '',
  summary_hi TEXT NOT NULL,
  summary_en TEXT NOT NULL,
  elig_hi TEXT NOT NULL,
  elig_en TEXT NOT NULL,
  keywords VARCHAR(500) NOT NULL DEFAULT '',
  content_hi MEDIUMTEXT NOT NULL,
  content_en MEDIUMTEXT NOT NULL,
  official_url VARCHAR(500) NOT NULL DEFAULT '',
  image VARCHAR(500) NOT NULL DEFAULT '',
  status ENUM('draft','published') NOT NULL DEFAULT 'draft',
  featured TINYINT(1) NOT NULL DEFAULT 0,
  seo_title VARCHAR(255) NOT NULL DEFAULT '',
  seo_desc VARCHAR(500) NOT NULL DEFAULT '',
  sort INT NOT NULL DEFAULT 0,
  author_id INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY type_slug (type, slug),
  KEY status_type (status, type),
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS menus (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  location ENUM('header','footer') NOT NULL,
  label_hi VARCHAR(160) NOT NULL,
  label_en VARCHAR(160) NOT NULL DEFAULT '',
  url VARCHAR(500) NOT NULL,
  new_tab TINYINT(1) NOT NULL DEFAULT 0,
  sort INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS media (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  path VARCHAR(500) NOT NULL,
  name VARCHAR(255) NOT NULL,
  size INT UNSIGNED NOT NULL DEFAULT 0,
  uploaded_by INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS links (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(80) NOT NULL UNIQUE,
  target VARCHAR(1000) NOT NULL,
  title VARCHAR(255) NOT NULL DEFAULT '',
  created_by INT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS visits (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ts DATETIME NOT NULL,
  visitor_id CHAR(16) NOT NULL,
  session_id CHAR(16) NOT NULL,
  path VARCHAR(500) NOT NULL,
  referrer VARCHAR(1000) NOT NULL DEFAULT '',
  ref_host VARCHAR(190) NOT NULL DEFAULT '',
  source VARCHAR(60) NOT NULL DEFAULT '',
  utm_source VARCHAR(120) NOT NULL DEFAULT '',
  utm_medium VARCHAR(120) NOT NULL DEFAULT '',
  utm_campaign VARCHAR(120) NOT NULL DEFAULT '',
  ip VARCHAR(45) NOT NULL,
  country VARCHAR(80) NOT NULL DEFAULT '',
  region VARCHAR(120) NOT NULL DEFAULT '',
  city VARCHAR(120) NOT NULL DEFAULT '',
  device VARCHAR(20) NOT NULL DEFAULT '',
  os VARCHAR(40) NOT NULL DEFAULT '',
  browser VARCHAR(40) NOT NULL DEFAULT '',
  lang VARCHAR(20) NOT NULL DEFAULT '',
  user_agent VARCHAR(500) NOT NULL DEFAULT '',
  KEY ts (ts), KEY path (path(120)), KEY ip (ip), KEY visitor (visitor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS clicks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ts DATETIME NOT NULL,
  visitor_id CHAR(16) NOT NULL DEFAULT '',
  session_id CHAR(16) NOT NULL DEFAULT '',
  page VARCHAR(500) NOT NULL DEFAULT '',
  url VARCHAR(1000) NOT NULL,
  link_text VARCHAR(255) NOT NULL DEFAULT '',
  link_id INT UNSIGNED NULL,
  is_external TINYINT(1) NOT NULL DEFAULT 0,
  ref_host VARCHAR(190) NOT NULL DEFAULT '',
  ip VARCHAR(45) NOT NULL,
  country VARCHAR(80) NOT NULL DEFAULT '',
  region VARCHAR(120) NOT NULL DEFAULT '',
  city VARCHAR(120) NOT NULL DEFAULT '',
  device VARCHAR(20) NOT NULL DEFAULT '',
  os VARCHAR(40) NOT NULL DEFAULT '',
  browser VARCHAR(40) NOT NULL DEFAULT '',
  KEY ts (ts), KEY url (url(120)), KEY ip (ip)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ip_geo (
  ip VARCHAR(45) PRIMARY KEY,
  country VARCHAR(80) NOT NULL DEFAULT '',
  region VARCHAR(120) NOT NULL DEFAULT '',
  city VARCHAR(120) NOT NULL DEFAULT '',
  isp VARCHAR(190) NOT NULL DEFAULT '',
  fetched_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activity_log (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id INT UNSIGNED NULL,
  action VARCHAR(80) NOT NULL,
  details VARCHAR(500) NOT NULL DEFAULT '',
  ip VARCHAR(45) NOT NULL DEFAULT '',
  KEY ts (ts)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS login_attempts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ip VARCHAR(45) NOT NULL,
  ts DATETIME NOT NULL,
  KEY ip_ts (ip, ts)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
